#!/bin/bash
sleep 0.5
wmctrl -r :ACTIVE: -e 0,0,734,120,100
wmctrl -r :ACTIVE: -b add,above
wmctrl -r :ACTIVE: -b add,skip_pager
wmctrl -r :ACTIVE: -b add,sticky

while true
do 
	y=` free -h | awk 'NR==3{print "ram:"$3"/"$4}'`
	x=`date +%H:%M:%S\ \ %d/%m`
	z=`acpi | awk '{print $4}'`
	v=`uptime -p | awk '{print $2"\:"$4}'`
	clear;
	echo  $x $z
	echo $y 
	sleep 1;
done
