#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
shopt -s expand_aliases
source /data/archbkp/p.sh
STR2=$STR
DEFAULT=0
if [ $1 = "-h" ]
then
	echo -e "${bold}usage: \n${bold}ttt ${normal}<Time> <message>\n	<Time> is the time to wait\
	\n	<message> is the message to display when \"Time\" time elapsed\
	\n\n${bold}ttt ${normal}<Time>\n	will just wait and display default message\n"
	exit 0
fi
if [ -z "$1" ]
then 
        time="$DEFAULT"
else
        time="$1"
        let time=(time*60)
fi
if [ -z "$2" ]
then
	msg="Alarm finished"
else
	msg=$2
fi
sleep $time
notify-send "$msg"
exit 0



