#!/bin/bash
/data/archbkp/raise/calendar
if [ $? -eq 0 ]
then
exit 0
fi
terwin=$(xdotool getactivewindow)
 google-chrome --user-data-dir=/data/google-chrome/ --profile-directory="Default" --app=http://calendar.google.com/calendar/gp#~calendar:view=m & > /dev/null 2>&1
echo "launching calendar"
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/calendar
echo $x > /data/archbkp/appsID/calendar
