#!/bin/bash
/data/archbkp/raise/generalRaise chrome3
if [ $? -eq 0 ]
then
exit 0
fi

terwin=$(xdotool getactivewindow)
google-chrome --user-data-dir=/data/google-chrome/ --profile-directory="Profile 3"  --ssl-version-min=tls1  & > /dev/null 2>&1
x=$(xdotool getactivewindow)

while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/chrome3
echo $x > /data/archbkp/appsID/chrome3
echo $x > /data/archbkp/appsID/chromeIDs/chrome3

