#!/bin/bash
/data/archbkp/raise/generalRaise files2
if [ $? -eq 0 ]
then
exit 0
fi

terwin=$(xdotool getactivewindow)
thunar & > /dev/null 2>&1
echo "launching calculator"
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
echo $x > /data/archbkp/appsID/files2

xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/filesPid2
