#!/bin/bash
/data/archbkp/raise/fin
if [ $? -eq 0 ]
then
exit 0
fi

terwin=$(xdotool getactivewindow)
google-chrome --user-data-dir=/data/google-chrome/ --profile-directory="Default" --app=https://www.google.com/finance?ei=OXNSWMGoMZuMswG_wYaQAQ & > /dev/null 2>&1
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/fin
echo $x > /data/archbkp/appsID/fin
