#!/bin/bash
/data/archbkp/raise/messengerVR
if [ $? -eq 0 ]
then
exit 0
fi

terwin=$(xdotool getactivewindow)
 google-chrome --user-data-dir=/data/google-chrome/ --profile-directory="Profile 1" --app=http://www.messenger.com & > /dev/null 2>&1
echo "launching messenger VR"
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
echo $x > /data/archbkp/appsID/messengerVR

xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/appspidVR
