#!/bin/bash
/data/archbkp/raise/generalRaise server
if [ $? -eq 0 ]
then
	exit 0
fi

terwin=$(xdotool getactivewindow)
xfce4-terminal -e "ssh mdahamshi.casacam.net" --maximize  & > /dev/null 2>&1
echo "launching server window"
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
echo $x > /data/archbkp/appsID/server

xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/server
