#!/bin/bash
/data/archbkp/raise/generalRaise web
if [ $? -eq 0 ]
then
exit 0
fi

terwin=$(xdotool getactivewindow)
epiphany-browser & > /dev/null 2>&1
x=$(xdotool getactivewindow)

while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done
xprop -id `xdotool getactivewindow` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$' > /data/archbkp/pids/web
echo $x > /data/archbkp/appsID/web

