#!/bin/bash
terwin=$(xdotool getactivewindow)
vboxmanage startvm win10
x=$(xdotool getactivewindow)
while [ $x -eq $terwin ] 
do
sleep 0.5
x=$(xdotool getactivewindow)
done

echo $x > /data/archbkp/appsID/win10


