#!/bin/bash
wmctrl  -R win10
vboxmanage controlvm win10 resume
sleep 0.1
win10=$(xdotool getactivewindow)
echo $win10  > /data/archbkp/appsID/win10
if [ $win10 -eq "$(cat /data/archbkp/appsID/last)" ]
then
	echo 0 > /data/archbkp/appsID/last
fi

